name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - run: go mod download -x
      - run: make release
        env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

